Here is how you can load the datasets with S3
1. In Config file: LOAD_FROM_S3=True
2. Enter you SSP Cloud secrets in a .env file (see READme)

In [1]:
#Imports
import s3fs
import pandas as pd

from src.data_processing.data_load import data_loading
from src.data_processing.data_processing import DataProcessor

In [2]:
#To load data the from the different files directly
df_portefeuille, df_consommations, df_reclamations, df_interactions, df_impayes= data_loading("training")

In [2]:
#To load and process the data of a specific set (training, validation, evaluation) without normalisation of numerical values
processor = DataProcessor(mode="training")
df = processor.run(optional_normalisation=False)

In [13]:
df

,client_age_souscripteur,client_ro_souscripteur,client_code_postal,client_departement,client_a_conjoint,client_nb_enfants,client_nb_assures_contrat,client_a_garantie_prevoyance,client_produit,client_garantie_base,...,recla_canal_entrant_principale_E-mail,recla_canal_entrant_principale_Formulaire web,recla_canal_entrant_principale_Réseaux sociaux,recla_canal_entrant_principale_Téléphone,recla_canal_entrant_principale_Valeur non référencée,recla_canal_entrant_secondaire_Courrier,recla_canal_entrant_secondaire_E-mail,recla_canal_entrant_secondaire_Formulaire web,recla_canal_entrant_secondaire_Réseaux sociaux,recla_canal_entrant_secondaire_Téléphone
0,97,0.123033,69100,69,0.0,0.0,1.0,0,0.021672,0.021739,...,0,0,0,0,0,0,0,0,0,0
1,95,0.123033,26230,26,0.0,0.0,1.0,1,0.021672,0.021791,...,0,0,0,0,0,0,0,0,0,0
2,88,0.062628,69760,69,1.0,0.0,2.0,0,0.021672,0.021739,...,0,0,0,0,0,0,0,0,0,0
3,95,0.062628,69003,69,0.0,0.0,1.0,0,0.021672,0.021791,...,0,0,0,0,0,0,0,0,0,0
4,90,0.062628,69100,69,1.0,0.0,2.0,1,0.021672,0.021791,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132571,36,0.123033,74140,74,0.0,0.0,1.0,0,0.030794,0.033770,...,0,0,0,0,0,0,0,0,0,0
132572,63,0.123033,17443,17,0.0,0.0,1.0,0,0.013863,0.012089,...,0,0,0,0,0,0,0,0,0,0
132573,25,0.123033,74200,74,0.0,0.0,1.0,0,0.030794,0.022051,...,0,0,0,0,0,0,0,0,0,0
132574,22,0.123033,97215,97,0.0,0.0,1.0,1,0.058163,0.062196,...,0,0,0,0,0,0,0,0,0,0
132575,40,0.062628,95300,95,0.0,0.0,1.0,0,0.058548,0.065918,...,0,0,0,0,0,0,0,0,0,0

In [16]:
#Same but with normalisation of numerical values
processor = DataProcessor(mode="training")
df_norm = processor.run(optional_normalisation=True)

In [ ]:
df_norm #now age is normalised (better to be processed by a linear model)

,client_age_souscripteur,client_ro_souscripteur,client_code_postal,client_departement,client_a_conjoint,client_nb_enfants,client_nb_assures_contrat,client_a_garantie_prevoyance,client_produit,client_garantie_base,...,recla_canal_entrant_principale_E-mail,recla_canal_entrant_principale_Formulaire web,recla_canal_entrant_principale_Réseaux sociaux,recla_canal_entrant_principale_Téléphone,recla_canal_entrant_principale_Valeur non référencée,recla_canal_entrant_secondaire_Courrier,recla_canal_entrant_secondaire_E-mail,recla_canal_entrant_secondaire_Formulaire web,recla_canal_entrant_secondaire_Réseaux sociaux,recla_canal_entrant_secondaire_Téléphone
0,2.040562,0.558597,0.447000,0.454435,0.0,0.0,-0.595937,0,-1.366055,-1.299895,...,0,0,0,0,0,0,0,0,0,0
1,1.919114,0.558597,-1.068101,-1.064775,0.0,0.0,-0.595937,1,-1.366055,-1.299120,...,0,0,0,0,0,0,0,0,0,0
2,1.494049,-1.844826,0.470326,0.454435,1.0,0.0,0.706991,0,-1.366055,-1.299895,...,0,0,0,0,0,0,0,0,0,0
3,1.919114,-1.844826,0.443572,0.454435,0.0,0.0,-0.595937,0,-1.366055,-1.299120,...,0,0,0,0,0,0,0,0,0,0
4,1.615496,-1.844826,0.447000,0.454435,1.0,0.0,0.706991,1,-1.366055,-1.299120,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132571,-1.663582,0.558597,0.625123,0.631087,0.0,0.0,-0.595937,0,-1.223350,-1.120666,...,0,0,0,0,0,0,0,0,0,0
132572,-0.024043,0.558597,-1.378650,-1.382749,0.0,0.0,-0.595937,0,-1.488218,-1.443664,...,0,0,0,0,0,0,0,0,0,0
132573,-2.331542,0.558597,0.627244,0.631087,0.0,0.0,-0.595937,0,-1.223350,-1.295253,...,0,0,0,0,0,0,0,0,0,0
132574,-2.513713,0.558597,1.440634,1.443687,0.0,0.0,-0.595937,1,-0.795205,-0.697177,...,0,0,0,0,0,0,0,0,0,0
132575,-1.420687,-1.844826,1.372955,1.373026,0.0,0.0,-0.595937,0,-0.789168,-0.641731,...,0,0,0,0,0,0,0,0,0,0

- The processing pipeline takes time (40 sec)
- **Alternative option**: load the already merged dataset (in parquet format) stored in S3, in the group-2 bucket "projet-bdc-alptis-g2" (around 10 sec)

In [3]:
#Use s3fs library to load the bucket where the parquet is stored
import Config 

fs = s3fs.S3FileSystem(
        endpoint_url='https://' + Config.S3_ENDPOINT,
        key=Config.S3_ACCESS_KEY,
        secret=Config.S3_SECRET_KEY,
        token=Config.S3_SESSION_TOKEN,
        client_kwargs={'verify': Config.S3_VERIFY_SSL}
    )

#Load the merged file (stored in parquet format) in the bucket
with fs.open(Config.MERGED_PARQUET_S3, "rb") as f:
    df_merged= pd.read_parquet(f)

Pour la suite: 
check les test non passés (pytest tests/test_processing.py)
split test/train dans un .py 
trainining.py, evaluation.py puis evaluation avec MLFlow

ATTENTION: QUAND CREE FONCTION FIT, VIRER CLIENT_CODE (SINON RISQUE DOVERFIT SUR CA)


X = df.drop(columns=[target_col, "client_code"])
y = df[target_col]

model.fit(X, y)
predictions = model.predict(X)

# Recoller via index — garanti aligné car même df
results = pd.DataFrame({
    "client_code":  df_ready["client_code"],  # depuis le même df
    "churn_predit": predictions
})