Here is how you can load the datasets with S3
1. In Config file: LOAD_FROM_S3=True
2. Enter you SSP Cloud secrets in a .env file (see READme)

In [1]:
#Imports
import s3fs
import pandas as pd
import logging
logging.basicConfig(level=logging.INFO)  #to be able to see the logging info+warnings(to only see warnings: logging.DEBUG)

from src.data_processing.data_load import data_loading
from src.data_processing.data_processing import DataProcessor

In [3]:
#To load data the from the different files directly
df_portefeuille, df_consommations, df_reclamations, df_interactions, df_impayes= data_loading("training")

/home/onyxia/work/Alptis-churn-prediction/src/data_processing/data_load.py:19: DtypeWarning: Columns (31,33) have mixed types. Specify dtype option on import or set low_memory=False.
  data_frames[key] = pd.read_csv(filepath, sep=";", index_col=False)

In [2]:
#To load and process the data of a specific set (training, validation, evaluation) without normalisation of numerical values
processor = DataProcessor(mode="training")
df = processor.run(optional_normalisation=False)

INFO:src.data_processing.data_processing:Dropped columns from dataset: ['client_structure_familiale', 'client_nom_banque', 'client_nps_verbatim_n', 'client_nps_verbatim_n_moins1', 'impaye_nb_actions', 'impaye_montant_total', 'impaye_duree_max_action_jours', 'impaye_action_1er_impaye', 'impaye_action_1ere_lettre_relance', 'impaye_action_2eme_impaye', 'impaye_action_annonce_contentieux', 'impaye_action_en_recouvrement', 'impaye_action_mise_en_demeure', 'impaye_action_suspension_garanties', 'interaction_historique_mail', 'client_nps_date_reponse_n_moins1_jours', 'client_nps_date_reponse_n_jours']
INFO:src.data_processing.data_processing:Columns that are One-hot encoded: ['client_mode_paiement', 'courtier_reseau_courtage', 'courtier_segmentation_interne', 'courtier_type_commission', 'recla_canal_entrant_principale', 'recla_canal_entrant_secondaire']
INFO:src.data_processing.data_processing:Columns that are Target encoded: ['client_ro_souscripteur', 'client_produit', 'client_garantie_base', 'client_garantie_base_plus_options', 'client_millesime_tarifaire_produit', 'client_zone_tarifaire', 'client_type_zone_tarifaire']
INFO:src.data_processing.data_processing:Columns that are Ordinal encoded: dict_items([('client_frequence_paiement', {'SEM': 0, 'MS': 1, 'TRIM': 2, 'AN': 3}), ('age_categories', {'child': 0, 'young': 1, 'adult': 2, 'mature': 3, 'middle aged': 4, 'senior': 5, 'senior plus': 6}), ('courtier_anciennete_categories', {'new': 0, 'recent': 1, 'stable': 2, 'old': 3, 'very old': 4, 'ancient': 5})])

In [7]:
processor = DataProcessor(mode="training")
processor.manual_preprocessing(df_portefeuille, df_consommations, df_reclamations, df_interactions, df_impayes)

INFO:src.data_processing.data_processing:Dropped columns from dataset: ['client_structure_familiale', 'client_nom_banque', 'client_nps_verbatim_n', 'client_nps_verbatim_n_moins1', 'impaye_nb_actions', 'impaye_montant_total', 'impaye_duree_max_action_jours', 'impaye_action_1er_impaye', 'impaye_action_1ere_lettre_relance', 'impaye_action_2eme_impaye', 'impaye_action_annonce_contentieux', 'impaye_action_en_recouvrement', 'impaye_action_mise_en_demeure', 'impaye_action_suspension_garanties', 'interaction_historique_mail']

,client_code,client_age_souscripteur,client_ro_souscripteur,client_code_postal,client_departement,client_a_conjoint,client_nb_enfants,client_nb_assures_contrat,client_a_garantie_prevoyance,client_produit,...,interaction_nb_transferts_reclamation,interaction_nb_transferts_gestion,interaction_nb_transferts_commercial,interaction_nb_transferts_externalises,age_categories,courtier_anciennete_categories,client_nps_date_reponse_n_moins1_jours,client_nps_date_reponse_n_jours,client_date_debut_effet_garantie_mois,dernier_paiement_consommation_mois
0,21736,97,SS,69100,69,0.0,0.0,1.0,0,produit_21,...,0.0,0.0,0.0,0.0,senior plus,very old,-1.0,-1.0,766,1.0
1,22037,95,SS,26230,26,0.0,0.0,1.0,1,produit_21,...,0.0,1.0,0.0,1.0,senior plus,old,-1.0,-1.0,322,1.0
2,22331,88,TNS,69760,69,1.0,0.0,2.0,0,produit_21,...,0.0,5.0,0.0,7.0,senior plus,very old,-1.0,-1.0,740,1.0
3,22604,95,TNS,69003,69,0.0,0.0,1.0,0,produit_21,...,0.0,0.0,0.0,0.0,senior plus,old,-1.0,-1.0,359,1.0
4,22702,90,TNS,69100,69,1.0,0.0,2.0,1,produit_21,...,0.0,4.0,0.0,8.0,senior plus,very old,-1.0,-1.0,727,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132571,16204966,36,SS,74140,74,0.0,0.0,1.0,0,produit_32,...,0.0,1.0,0.0,0.0,mature,old,-1.0,-1.0,1,-1.0
132572,16205008,63,SS,17443,17,0.0,0.0,1.0,0,produit_20,...,0.0,0.0,0.0,0.0,senior,stable,-1.0,-1.0,1,-1.0
132573,16205281,25,SS,74200,74,0.0,0.0,1.0,0,produit_32,...,0.0,0.0,0.0,0.0,young,new,-1.0,-1.0,1,-1.0
132574,16206464,22,SS,97215,97,0.0,0.0,1.0,1,produit_18,...,0.0,0.0,0.0,0.0,young,stable,-1.0,-1.0,1,-1.0
132575,16206912,40,TNS,95300,95,0.0,0.0,1.0,0,produit_36,...,0.0,0.0,0.0,0.0,mature,new,-1.0,-1.0,1,-1.0

In [10]:
#Same but with normalisation of numerical values
processor = DataProcessor(mode="training")
df_norm = processor.run(optional_normalisation=True)

INFO:src.data_processing.data_processing:Dropped columns from dataset: ['client_structure_familiale', 'client_nom_banque', 'client_nps_verbatim_n', 'client_nps_verbatim_n_moins1', 'impaye_nb_actions', 'impaye_montant_total', 'impaye_duree_max_action_jours', 'impaye_action_1er_impaye', 'impaye_action_1ere_lettre_relance', 'impaye_action_2eme_impaye', 'impaye_action_annonce_contentieux', 'impaye_action_en_recouvrement', 'impaye_action_mise_en_demeure', 'impaye_action_suspension_garanties', 'interaction_historique_mail']
INFO:src.data_processing.data_processing:Encoded with one-hot encoding: ['client_mode_paiement', 'client_frequence_paiement', 'courtier_reseau_courtage', 'courtier_segmentation_interne', 'courtier_type_commission', 'recla_canal_entrant_principale', 'recla_canal_entrant_secondaire']
INFO:src.data_processing.data_processing:Encoded with target encoding: ['client_ro_souscripteur', 'client_produit', 'client_garantie_base', 'client_garantie_base_plus_options', 'client_millesime_tarifaire_produit', 'client_zone_tarifaire', 'client_type_zone_tarifaire']
INFO:src.data_processing.data_processing:Encoded with ordinal encoding: {'age_categories': ['young', 'adult', 'mature', 'middle aged', 'senior', 'senior plus'], 'courtier_anciennete_categories': ['new', 'recent', 'stable', 'old', 'very old']}
INFO:root:Normalisation applied on numerical values
INFO:src.data_processing.data_processing:Normalized: ['client_code', 'client_age_souscripteur', 'client_ro_souscripteur', 'client_code_postal', 'client_departement', 'client_nb_assures_contrat', 'client_produit', 'client_garantie_base', 'client_garantie_base_plus_options', 'client_millesime_tarifaire_produit', 'client_zone_tarifaire', 'client_type_zone_tarifaire', 'client_anciennete_contrat_annees', 'client_cotisations_annualisees_n_moins2', 'client_cotisations_annualisees_n_moins1', 'client_cotisations_annualisees_n', 'client_cotisations_annualisees_n_plus1', 'client_nps_note_reco_n', 'client_nps_note_reco_n_moins1', 'courtier_code_partenaire', 'courtier_anciennete_annees', 'courtier_code_apporteur', 'courtier_nb_affaires_n_moins1', 'courtier_nb_radiations_n_moins1', 'courtier_nb_affaires_n_moins2', 'courtier_nb_radiations_n_moins2', 'recla_nombre', 'recla_initiateur_client', 'recla_delais_court', 'recla_delais_moyen', 'recla_latest_jours', 'nb_decomptes', 'nb_decomptes_hospitalisation', 'nb_decomptes_soins_medicaux', 'nb_decomptes_pharmacie', 'nb_decomptes_optique', 'nb_decomptes_dentaire', 'nb_decomptes_divers', 'nb_jours_forfait_journalier', 'nb_jours_chambre_particuliere', 'nb_protheses_dentaires', 'remb_alptis', 'remb_alptis_hospitalisation', 'remb_alptis_soins_medicaux', 'remb_alptis_pharmacie', 'remb_alptis_optique', 'remb_alptis_dentaire', 'remb_alptis_divers', 'remb_ro', 'remb_ro_hospitalisation', 'remb_ro_soins_medicaux', 'remb_ro_pharmacie', 'remb_ro_optique', 'remb_ro_dentaire', 'remb_ro_divers', 'frais_reels', 'frais_reels_hospitalisation', 'frais_reels_soins_medicaux', 'frais_reels_pharmacie', 'frais_reels_optique', 'frais_reels_dentaire', 'frais_reels_divers', 'reste_a_charge', 'reste_a_charge_hospitalisation', 'reste_a_charge_soins_medicaux', 'reste_a_charge_pharmacie', 'reste_a_charge_optique', 'reste_a_charge_dentaire', 'reste_a_charge_divers', 'interaction_nb_total', 'interaction_motif_dentaire', 'interaction_motif_frais_courants', 'interaction_motif_hospitalisation', 'interaction_motif_medecine_douce', 'interaction_motif_optique', 'interaction_motif_tiers_payant', 'interaction_motif_teletransmission', 'interaction_motif_autre', 'interaction_service_cotisations_&_recouvrements', 'interaction_service_prestations_sante', 'interaction_service_suivi_du_contrat', 'interaction_autres_services', 'interaction_canal_telephone_nb', 'interaction_nb_transferts_gestion', 'interaction_nb_transferts_externalises', 'client_nps_date_reponse_n_moins1_jours', 'client_nps_date_reponse_n_jours', 'dernier_paiement_consommation_mois']

In [ ]:
df_norm #now for example, age is normalised (better to be processed by a linear model OR other specific models)

0         5.0
1         5.0
2         5.0
3         5.0
4         5.0
         ...
132571    2.0
132572    4.0
132573    0.0
132574    0.0
132575    2.0
Name: age_categories, Length: 132576, dtype: float64

**VERY IMPORTANT**

*The test/validation set need to be pre-processed using encoder/scaler that were fitted on training set* to avoid data-leakage (due to target-encoding, normalisation, ...).
To do see, see below: 

1. method df.run(): fit + transform the dataframe --> to use for training
2. method df.run_transform(): only transform the dataframe, using pre-saved args for target-encoding, scaler, ordinal encoding,... --> to use for validation/test

In [4]:
#1. Pre-process training data (scaler and encoder are saved during this process)
train_processor = DataProcessor(mode="training")
df_train = train_processor.run()  #fit training set and save arguments (scaler, ordinal map, target_encoding_maps, ...)

#2. Pre-process test data (by using the same scaler/encoder fitted on training dataset)
test_processor = DataProcessor(mode="evaluation")

#  HERE:  Reuse the same pre-processor fitted on training dataset (so no data-leakage with target-encoding, normalisation...)
test_processor.target_encoding_maps = train_processor.target_encoding_maps
test_processor.ordinal_maps          = train_processor.ordinal_maps
test_processor.encoded_columns       = train_processor.encoded_columns
test_processor.scaler                = train_processor.scaler
test_processor.normalized_columns    = train_processor.normalized_columns

df_test = test_processor.run_transform() #pre-process test data using same args

INFO:src.data_processing.data_processing:Dropped columns from dataset: ['client_structure_familiale', 'client_nom_banque', 'client_nps_verbatim_n', 'client_nps_verbatim_n_moins1', 'impaye_nb_actions', 'impaye_montant_total', 'impaye_duree_max_action_jours', 'impaye_action_1er_impaye', 'impaye_action_1ere_lettre_relance', 'impaye_action_2eme_impaye', 'impaye_action_annonce_contentieux', 'impaye_action_en_recouvrement', 'impaye_action_mise_en_demeure', 'impaye_action_suspension_garanties', 'interaction_historique_mail', 'client_nps_date_reponse_n_moins1_jours', 'client_nps_date_reponse_n_jours']
INFO:src.data_processing.data_processing:Columns that are One-hot encoded: ['client_mode_paiement', 'courtier_reseau_courtage', 'courtier_segmentation_interne', 'courtier_type_commission', 'recla_canal_entrant_principale', 'recla_canal_entrant_secondaire']
INFO:src.data_processing.data_processing:Columns that are Target encoded: ['client_ro_souscripteur', 'client_produit', 'client_garantie_base', 'client_garantie_base_plus_options', 'client_millesime_tarifaire_produit', 'client_zone_tarifaire', 'client_type_zone_tarifaire']
INFO:src.data_processing.data_processing:Columns that are Ordinal encoded: dict_items([('client_frequence_paiement', {'SEM': 0, 'MS': 1, 'TRIM': 2, 'AN': 3}), ('age_categories', {'young': 0, 'adult': 1, 'mature': 2, 'middle aged': 3, 'senior': 4, 'senior plus': 5}), ('courtier_anciennete_categories', {'new': 0, 'recent': 1, 'stable': 2, 'old': 3, 'very old': 4})])
INFO:src.data_processing.data_processing:Dropped columns from dataset: ['client_structure_familiale', 'client_nom_banque', 'client_nps_verbatim_n', 'client_nps_verbatim_n_moins1', 'impaye_nb_actions', 'impaye_montant_total', 'impaye_duree_max_action_jours', 'impaye_action_1er_impaye', 'impaye_action_1ere_lettre_relance', 'impaye_action_2eme_impaye', 'impaye_action_annonce_contentieux', 'impaye_action_en_recouvrement', 'impaye_action_mise_en_demeure', 'impaye_action_suspension_garanties', 'interaction_historique_mail', 'client_nps_date_reponse_n_moins1_jours', 'client_nps_date_reponse_n_jours']

In [ ]:
#Visualise saved args of training set (ex: target_encoding_maps)
train_processor.target_encoding_maps #ex: for each column target-encoded, save the target-mean of each values

{'client_ro_souscripteur': client_ro_souscripteur
 A           0.000000
 AM          0.068583
 AMEXA       0.074365
 ASSIM_SS    0.052632
 CFE         0.000000
 DDOM        0.000000
 EDOM        0.000000
 F           0.000000
 MGEN        0.125817
 MONACO      0.000000
 NOTAIRE     0.125000
 PRAGA       0.000000
 PT          0.000000
 RAM         0.042394
 SA          0.100908
 SNCF        0.140845
 SS          0.123033
 SSM         0.210526
 TNS         0.062628
 Name: target_resiliation_6mois, dtype: float64,
 'client_produit': client_produit
 produit_1     0.053705
 produit_10    0.067890
 produit_11    0.066327
 produit_12    0.112782
 produit_13    0.000000
 produit_14    0.022305
 produit_15    0.038911
 produit_16    0.052288
 produit_17    0.081159
 produit_18    0.058163
 produit_19    0.022013
 produit_2     0.071063
 produit_20    0.013863
 produit_21    0.021672
 produit_22    0.046537
 produit_23    0.059028
 produit_24    0.006623
 produit_25    0.146186
 produit_26    0.149228
 produit_27    0.000000
 produit_28    0.000000
 produit_29    0.140784
 produit_3     0.042945
 produit_30    0.200479
 produit_31    0.035077
 produit_32    0.030794
 produit_33    0.030581
 produit_34    0.047702
 produit_36    0.058548
 produit_37    0.177149
 produit_38    0.019934
 produit_39    0.001373
 produit_4     0.117647
 produit_40    0.001206
 produit_41    0.058824
 produit_42    0.066421
 produit_43    0.082811
 produit_44    0.000000
 produit_45    0.137500
 produit_46    0.115282
 produit_47    0.112903
 produit_5     0.084848
 produit_6     0.070136
 produit_7     0.019868
 produit_8     0.068607
 produit_9     0.060413
 Name: target_resiliation_6mois, dtype: float64,
 'client_garantie_base': client_garantie_base
 garantie_1      0.111111
 garantie_10     0.068966
 garantie_100    0.012089
 garantie_101    0.000000
 garantie_102    0.160000
                   ...
 garantie_95     0.090909
 garantie_96     0.000000
 garantie_97     0.022013
 garantie_98     0.014351
 garantie_99     0.016892
 Name: target_resiliation_6mois, Length: 206, dtype: float64,
 'client_garantie_base_plus_options': client_garantie_base_plus_options
 garantie_1             0.111111
 garantie_10            0.068966
 garantie_100           0.012089
 garantie_101           0.000000
 garantie_102           0.160000
                          ...
 garantie_96            0.000000
 garantie_97            0.022013
 garantie_98            0.014351
 garantie_99            0.016920
 garantie_99 + surco    0.000000
 Name: target_resiliation_6mois, Length: 436, dtype: float64,
 'client_millesime_tarifaire_produit': client_millesime_tarifaire_produit
 2015                                                         0.082363
 2016                                                         0.095437
 2017                                                         0.101920
 2018                                                         0.091749
 2019                                                         0.100165
 2020                                                         0.102953
 2021                                                         0.152054
 2021_BIS                                                     0.172989
 2022                                                         0.236086
 2023                                                         0.223077
 2023_BIS                                                     0.089777
 2024                                                         0.003755
 Portefeuille assuré en 2012-2018                             0.072330
 Portefeuille assuré en 2017-2018                             0.143852
 Portefeuille sur millésime 2019 (à compter du 15/10/2018)    0.080675
 Portefeuille sur millésime 2020                              0.085714
 Portefeuille sur millésime 2021                              0.074449
 Portefeuille sur millésime 2022                              0.090023
 Portefeuille sur millésime 2023                              0.027261
 Portefeuille sur millésime 2024                              0.000000
 Sans millésime                                               0.039723
 Tarif 2021                                                   0.127820
 Tarif 2022                                                   0.242709
 Tarif 2023                                                   0.137767
 Tarif 2024                                                   0.000728
 Name: target_resiliation_6mois, dtype: float64,
 'client_zone_tarifaire': client_zone_tarifaire
 1         0.019108
 2         0.037037
 3         0.027542
 A         0.048649
 B         0.045936
             ...
 VERAZ1    0.121212
 VERAZ2    0.115942
 VERAZ3    0.095890
 WISZ1     0.119048
 WISZ2     0.100000
 Name: target_resiliation_6mois, Length: 173, dtype: float64,
 'client_type_zone_tarifaire': client_type_zone_tarifaire
 1-2-3             0.031589
 A-B-C-D-E         0.056530
 CLAREA1           0.062640
 CLAREA2           0.072906
 CLAREA34HS        0.087822
 D1G13             0.061866
 D1V2              0.071602
 D2G13             0.065032
 D2V2              0.045031
 D3G13             0.074783
 D3V2              0.057644
 D4G13             0.081761
 D4V2              0.071006
 DIV1              0.068452
 DIV2              0.069079
 DIV3              0.071111
 DIV4              0.061856
 DS1               0.052039
 DS2               0.074510
 DS3               0.082251
 DS4               0.087629
 FID               0.112782
 LUMI-1            0.053496
 LUMI-2            0.062196
 LUMI-3            0.053794
 LUMI-4H           0.070812
 MILTIS            0.149228
 Medico            0.027894
 Non Zoné          0.006623
 Non zoné          0.100614
 OFFRE_MILTISR1    0.122667
 OFFRE_MILTISR2    0.237113
 S1-S2-S3-S4-S5    0.065141
 SANTE2            0.151415
 SANTE3            0.156769
 SANTE4            0.102321
 SANTE5            0.079535
 SANTEECO1         0.136905
 SLTPRO            0.037709
 SLTPRO1           0.062500
 SLTPRO4           0.054932
 SLTSEN            0.163684
 SLTSEN1           0.201180
 SLTSEN4           0.145680
 SPI200            0.042254
 SPI300            0.044444
 SPI400            0.011905
 SPI500            0.000000
 SPIV3             0.047702
 VERA              0.115282
 WIS               0.112903
 Name: target_resiliation_6mois, dtype: float64}

## New external column: client_revenu_commune_2021

In [ ]:
df[["client_departement","client_code_postal","client_revenu_commune_2021"]] #new column on revenu (external)

        client_departement client_code_postal  client_revenu_commune_2021
0                       69              69100                     21540.0
1                       26              26230                     22350.0
2                       26              26230                     24740.0
3                       26              26230                     23960.0
4                       26              26230                     24690.0
...                    ...                ...                         ...
694135                  97              97215                     19840.0
694136                  95              95300                     29520.0
694137                  95              95300                     29670.0
694138                  95              95300                     33270.0
694139                  95              95300                     22340.0

[694140 rows x 3 columns]

In [39]:
#check coherence by look at richer and poorer departement of France
(df.groupby("client_code_postal")["client_revenu_commune_2021"]
   .median()
   .nlargest(10)
   .reset_index())

  client_code_postal  client_revenu_commune_2021
0              92200                     48010.0
1              01220                     46650.0
2              74160                     45460.0
3              01280                     44430.0
4              78860                     44020.0
5              01170                     44010.0
6              78110                     42870.0
7              69370                     42270.0
8              01630                     42220.0
9              92430                     41740.0

In [40]:
#poorer commune
(df.groupby("client_code_postal")["client_revenu_commune_2021"]
   .median()
   .nsmallest(10)
   .reset_index())

  client_code_postal  client_revenu_commune_2021
0              97433                     13280.0
1              97413                     13780.0
2              97439                     14030.0
3              97470                     14550.0
4              59100                     14580.0
5              91350                     14790.0
6              09320                     14905.0
7              97442                     14910.0
8              97420                     14970.0
9              97440                     15080.0

It's coherent: 

Richest: 
- 92200 = Neuilly-sur-Seine
- 01220 = Divonne les bains (ville frontalière à la suisse)

Poorest: 
- 974... = Réunion
- 91350 = Grigny