Here is a toy example of different useful functions/tools/models/... we've developed during the project

In [4]:
#Librairies import
import pandas as pd
from merge_and_agregation import *
import warnings

warnings.filterwarnings("ignore")

### 1.How to aggregate a secondary file

First let's load our files

In [26]:
#Loading of the file
df_portefeuille=pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_portefeuille_2023_11.csv", sep=";")
df_reclamations= pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_reclamations_2023_11.csv", sep=";")
df_interactions=pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_interactions_2023_11.csv", sep=";")
df_impayes= pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_impayes_2023_11.csv", sep=";")
df_consommations= pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_consommations_2023_11.csv", sep=";")

As an example, let's agregate the DataFrame *interaction*. To do so we use the function *aggregate_interaction*

In [3]:
#As an example let's agregate the file aggregation
aggregate_interaction(df_interactions)

/home/onyxia/work/bdc-alptis-g2/merge_and_agregation.py:376: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_interaction_historique_mail = df_mail.groupby("client_code").apply(

,client_code,interaction_nb_total,interaction_motif_dentaire,interaction_motif_frais_courants,interaction_motif_hospitalisation,interaction_motif_medecine_douce,interaction_motif_optique,interaction_motif_tiers_payant,interaction_motif_teletransmission,interaction_motif_autre,interaction_service_cotisations_recouvrements,interaction_service_prestations_sante,interaction_service_suivi_du_contrat,interaction_autres_services,interaction_canal_telephone_nb,interaction_nb_transferts_reclamation,interaction_nb_transferts_gestion,interaction_nb_transferts_commercial,interaction_nb_transferts_externalises,interaction_historique_mail
0,22037,2,0,0,0,0,0,0,0,2,0,0,0,2,1.0,0,1,0,1,{'2023-01-24': 'xxpj0 xxobj Adhérent 3148 Mme...
1,22331,10,0,0,2,0,4,0,0,4,0,10,0,0,10.0,0,5,0,7,{}
2,22702,8,0,1,4,0,0,0,0,3,0,8,0,0,8.0,0,4,0,8,{}
3,23003,1,0,1,0,0,0,0,0,0,0,1,0,0,1.0,0,0,0,1,{}
4,23164,2,0,1,0,0,0,0,0,1,0,2,0,0,2.0,0,2,0,2,{}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65890,16201438,1,0,0,0,0,0,0,1,0,0,0,1,0,0.0,0,1,0,0,{'2023-11-29': 'xxpj0 Capture d’écran 2023-11...
65891,16201746,1,0,0,0,0,0,0,1,0,0,0,1,0,0.0,0,1,0,0,{'2023-11-29': 'xxpj0 AttestationDroits xxobj ...
65892,16201837,1,0,0,0,0,0,0,0,1,0,0,1,0,0.0,0,1,0,0,{'2023-11-28': 'xxpj0 Demande mutuelle flag_no...
65893,16203174,1,0,0,0,0,0,0,1,0,0,0,1,0,0.0,0,1,0,0,{'2023-11-29': 'xxpj0 AttestationDroits Ameli[...
65894,16204966,1,0,0,0,0,0,0,1,0,0,0,1,0,0.0,0,1,0,0,{'2023-11-28': 'xxpj0 AttestationDroits xxobj ...

### 2. How to aggregate, clean and merge all the tables

In [5]:
df=create_clean_aggregated_dataset(df_consommations=df_consommations, df_impayes=df_impayes, df_reclamations=df_reclamations, df_portefeuille=df_portefeuille, df_interactions=df_interactions)

In [27]:
[c for c in df.columns if c.startswith('interactions')]

#[c for c in df.columns if c in df_interactions.columns]

[]

In [23]:
df.columns

Index(['client_code', 'client_age_souscripteur', 'client_ro_souscripteur',
       'client_code_postal', 'client_departement', 'client_a_conjoint',
       'client_nb_enfants', 'client_structure_familiale',
       'client_nb_assures_contrat', 'client_a_garantie_prevoyance',
       ...
       'interaction_service_cotisations_recouvrements',
       'interaction_service_prestations_sante',
       'interaction_service_suivi_du_contrat', 'interaction_autres_services',
       'interaction_canal_telephone_nb',
       'interaction_nb_transferts_reclamation',
       'interaction_nb_transferts_gestion',
       'interaction_nb_transferts_commercial',
       'interaction_nb_transferts_externalises',
       'interaction_historique_mail'],
      dtype='object', length=135)

In [18]:
df[[c for c in df.columns if c.startswith(("frais", "remb", "nb_decomptes"))]].fillna(0)

,nb_decomptes,nb_decomptes_hospitalisation,nb_decomptes_soins_medicaux,nb_decomptes_pharmacie,nb_decomptes_optique,nb_decomptes_dentaire,nb_decomptes_divers,remb_alptis,remb_alptis_hospitalisation,remb_alptis_soins_medicaux,...,remb_ro_optique,remb_ro_dentaire,remb_ro_divers,frais_reels,frais_reels_hospitalisation,frais_reels_soins_medicaux,frais_reels_pharmacie,frais_reels_optique,frais_reels_dentaire,frais_reels_divers
0,23.0,0.0,2.0,20.0,0.0,0.0,1.0,526.35,0.00,32.27,...,0.0,0.0,239.10,1181.26,0.00,67.00,609.13,0.00,0.0,505.13
1,25.0,0.0,11.0,14.0,0.0,0.0,0.0,684.12,0.00,586.69,...,0.0,0.0,0.00,1642.47,0.00,1467.13,175.34,0.00,0.0,0.00
2,84.0,2.0,36.0,42.0,1.0,0.0,3.0,2004.84,294.00,1336.30,...,36.0,0.0,86.04,4509.60,318.66,3471.46,368.81,207.26,0.0,143.41
3,27.0,0.0,7.0,12.0,0.0,0.0,8.0,376.26,0.00,121.32,...,0.0,0.0,841.82,1550.61,0.00,355.06,128.64,0.00,0.0,1066.91
4,65.0,6.0,33.0,25.0,0.0,0.0,1.0,3128.94,1901.42,1030.78,...,0.0,0.0,55.02,5959.13,2856.54,2621.32,386.27,0.00,0.0,95.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
132572,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
132573,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
132574,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
132575,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00