Here is a toy example of different useful functions/tools/models/... we've developed during the project

In [1]:
#Librairies import
import pandas as pd
from merge_and_agregation import *

### 1.How to aggregate a secondary file

First let's load our files

In [2]:
#Loading of the file
df_portefeuille=pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_portefeuille_2023_11.csv", sep=";")
df_reclamations= pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_reclamations_2023_11.csv", sep=";")
df_interactions=pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_interactions_2023_11.csv", sep=";")
df_impayes= pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_impayes_2023_11.csv", sep=";")
df_consommations= pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_consommations_2023_11.csv", sep=";")

/tmp/ipykernel_239633/5455498.py:2: DtypeWarning: Columns (31,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df_portefeuille=pd.read_csv("s3://projet-bdc-data/alptis/training/apprentissage_portefeuille_2023_11.csv", sep=";")

As an example, let's agregate the DataFrame *interaction*. To do so we use the function *aggregate_interaction*

In [3]:
#As an example let's agregate the file aggregation
aggregate_interaction(df_interactions)

/home/onyxia/work/bdc-alptis-g2/merge_and_agregation.py:376: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_interaction_historique_mail = df_mail.groupby("client_code").apply(

,client_code,interaction_nb_total,interaction_motif_dentaire,interaction_motif_frais_courants,interaction_motif_hospitalisation,interaction_motif_medecine_douce,interaction_motif_optique,interaction_motif_tiers_payant,interaction_motif_teletransmission,interaction_motif_autre,interaction_service_cotisations_recouvrements,interaction_service_prestations_sante,interaction_service_suivi_du_contrat,interaction_autres_services,interaction_canal_telephone_nb,interaction_nb_transferts_reclamation,interaction_nb_transferts_gestion,interaction_nb_transferts_commercial,interaction_nb_transferts_externalises,interaction_historique_mail
0,22037,2,0,0,0,0,0,0,0,2,0,0,0,2,1.0,0,1,0,1,{'2023-01-24': 'xxpj0 xxobj Adhérent 3148 Mme...
1,22331,10,0,0,2,0,4,0,0,4,0,10,0,0,10.0,0,5,0,7,{}
2,22702,8,0,1,4,0,0,0,0,3,0,8,0,0,8.0,0,4,0,8,{}
3,23003,1,0,1,0,0,0,0,0,0,0,1,0,0,1.0,0,0,0,1,{}
4,23164,2,0,1,0,0,0,0,0,1,0,2,0,0,2.0,0,2,0,2,{}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65890,16201438,1,0,0,0,0,0,0,1,0,0,0,1,0,0.0,0,1,0,0,{'2023-11-29': 'xxpj0 Capture d’écran 2023-11...
65891,16201746,1,0,0,0,0,0,0,1,0,0,0,1,0,0.0,0,1,0,0,{'2023-11-29': 'xxpj0 AttestationDroits xxobj ...
65892,16201837,1,0,0,0,0,0,0,0,1,0,0,1,0,0.0,0,1,0,0,{'2023-11-28': 'xxpj0 Demande mutuelle flag_no...
65893,16203174,1,0,0,0,0,0,0,1,0,0,0,1,0,0.0,0,1,0,0,{'2023-11-29': 'xxpj0 AttestationDroits Ameli[...
65894,16204966,1,0,0,0,0,0,0,1,0,0,0,1,0,0.0,0,1,0,0,{'2023-11-28': 'xxpj0 AttestationDroits xxobj ...

### 2. How to aggregate Left merge and clean all the tables with portefeuille, based on client_code

In [4]:
agregate_and_merge(df_consommations=df_consommations, df_impayes=df_impayes, df_reclamations=df_reclamations, df_portefeuille=df_portefeuille, df_interactions=df_interactions)

/home/onyxia/work/bdc-alptis-g2/merge_and_agregation.py:251: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("client_code").apply(build_info_dict).reset_index(drop=True)
/home/onyxia/work/bdc-alptis-g2/merge_and_agregation.py:376: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_interaction_historique_mail = df_mail.groupby("client_code").apply(

,client_code,client_age_souscripteur,client_sexe_souscripteur,client_ro_souscripteur,client_code_postal,client_departement,client_departement_avant_changement_12_mois,client_a_conjoint,client_nb_enfants,client_structure_familiale,...,interaction_service_cotisations_recouvrements,interaction_service_prestations_sante,interaction_service_suivi_du_contrat,interaction_autres_services,interaction_canal_telephone_nb,interaction_nb_transferts_reclamation,interaction_nb_transferts_gestion,interaction_nb_transferts_commercial,interaction_nb_transferts_externalises,interaction_historique_mail
0,21736,97,F,SS,69100,69,NaN,0.0,0.0,femme ss enfant,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22037,95,F,SS,26230,26,NaN,0.0,0.0,femme ss enfant,...,0.0,0.0,0.0,2.0,1.0,0.0,1.0,0.0,1.0,{'2023-01-24': 'xxpj0 xxobj Adhérent 3148 Mme...
2,22331,88,M,TNS,69760,69,NaN,1.0,0.0,couple ss enfant,...,0.0,10.0,0.0,0.0,10.0,0.0,5.0,0.0,7.0,{}
3,22604,95,F,TNS,69003,69,NaN,0.0,0.0,femme ss enfant,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22702,90,M,TNS,69100,69,NaN,1.0,0.0,couple ss enfant,...,0.0,8.0,0.0,0.0,8.0,0.0,4.0,0.0,8.0,{}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132571,16204966,36,M,SS,74140,74,NaN,0.0,0.0,homme ss enfant,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,{'2023-11-28': 'xxpj0 AttestationDroits xxobj ...
132572,16205008,63,M,SS,17443,17,NaN,0.0,0.0,homme ss enfant,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132573,16205281,25,F,SS,74200,74,NaN,0.0,0.0,femme ss enfant,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132574,16206464,22,F,SS,97215,97,NaN,0.0,0.0,femme ss enfant,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132575,16206912,40,M,TNS,95300,95,NaN,0.0,0.0,homme ss enfant,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN